name: CI Quality Test

# Déclencheur : à chaque push ou pull request sur la branche main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Démarrer les conteneurs Docker
    - name: Start Docker Environment
      run: docker-compose up -d --build

    # 3. Attendre que la base de données soit prête
    # (MySQL prend quelques secondes pour s'initialiser)
    - name: Wait for Database
      run: |
        echo "Waiting for MySQL to be ready..."
        sleep 20

    # 4. Exécuter le script de test de qualité
    # L'option -T est cruciale pour désactiver l'allocation de pseudo-TTY (nécessaire en CI)
    - name: Run Quality Tests (q_test.php)
      run: docker-compose exec -T app php q_test.php

    # 5. Arrêter les conteneurs (Nettoyage)
    - name: Stop Containers
      if: always() # S'exécute même si les tests échouent
      run: docker-compose down
